#!/usr/bin/env bash

set -euo pipefail
umask 077

ipa_path="${1:?Usage: upload-testflight.sh <app-store-ipa> <log-directory>}"
log_dir="${2:?Usage: upload-testflight.sh <app-store-ipa> <log-directory>}"
signing_dir="${XBUILD_SIGNING_DIR:?XBUILD_SIGNING_DIR is required}"
output_dir="${XBUILD_OUTPUT_DIR:?XBUILD_OUTPUT_DIR is required}"

auth_method="${XBUILD_TESTFLIGHT_AUTH_METHOD:-}"
key_id="${XBUILD_ASC_KEY_ID:-}"
issuer_id="${XBUILD_ASC_ISSUER_ID:-}"
private_key_base64="${XBUILD_ASC_PRIVATE_KEY_BASE64:-}"
apple_id="${XBUILD_APPLE_ID:-}"
app_specific_password="${XBUILD_APP_SPECIFIC_PASSWORD:-}"
team_id="${XBUILD_APPLE_TEAM_ID:-}"

# A blank method keeps repositories configured by XBuild 1.5 and older working.
# Prefer their complete API-key triplet, otherwise use a complete Apple-ID pair.
if [[ -z "$auth_method" ]]; then
  if [[ -n "$key_id" && -n "$issuer_id" && -n "$private_key_base64" ]]; then
    auth_method="api-key"
  elif [[ -n "$apple_id" && -n "$app_specific_password" ]]; then
    auth_method="apple-id"
  fi
fi

case "$auth_method" in
  api-key)
    if [[ -z "$key_id" || -z "$issuer_id" || -z "$private_key_base64" ]]; then
      echo "::error title=TestFlight setup incomplete::API-key authentication requires Key ID, Issuer ID, and the .p8 private key."
      exit 44
    fi
    if [[ ! "$key_id" =~ ^[A-Z0-9]{10}$ ]]; then
      echo "::error title=Invalid App Store Connect Key ID::Expected 10 uppercase letters or digits."
      exit 44
    fi
    if [[ ! "$issuer_id" =~ ^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}$ ]]; then
      echo "::error title=Invalid App Store Connect Issuer ID::Expected a UUID."
      exit 44
    fi
    ;;
  apple-id)
    if [[ -z "$apple_id" || -z "$app_specific_password" || -z "$team_id" ]]; then
      echo "::error title=TestFlight setup incomplete::Apple-ID authentication requires Apple ID, app-specific password, and Apple Team ID."
      exit 44
    fi
    if (( ${#apple_id} > 254 )) || [[ "$apple_id" =~ [[:space:][:cntrl:]] ]]; then
      echo "::error title=Invalid Apple ID::Expected a single-line Apple ID without whitespace."
      exit 44
    fi
    if (( ${#app_specific_password} < 8 || ${#app_specific_password} > 128 )) ||
       [[ ! "$app_specific_password" =~ ^[A-Za-z0-9-]+$ ]]; then
      echo "::error title=Invalid app-specific password::Use the app-specific password generated by Apple, containing only letters, digits, and hyphens."
      exit 44
    fi
    if [[ ! "$team_id" =~ ^[A-Z0-9]{10}$ ]]; then
      echo "::error title=Invalid Apple Team ID::Expected 10 uppercase letters or digits."
      exit 44
    fi
    ;;
  "")
    echo "::error title=TestFlight setup incomplete::Configure either an App Store Connect API key or Apple ID with an app-specific password."
    exit 44
    ;;
  *)
    echo "::error title=Invalid TestFlight authentication::Expected api-key or apple-id."
    exit 44
    ;;
esac

ipa_path="$(python3 - "$ipa_path" "$output_dir" <<'PY'
import pathlib
import sys

ipa = pathlib.Path(sys.argv[1]).resolve(strict=True)
output = pathlib.Path(sys.argv[2]).resolve(strict=True)
try:
    ipa.relative_to(output)
except ValueError:
    print("::error title=Unsafe TestFlight path::The App Store IPA is outside XBuild's output directory.")
    raise SystemExit(44)
if ipa.suffix.lower() != ".ipa" or not ipa.is_file():
    print("::error title=App Store IPA missing::The TestFlight upload input is not an IPA file.")
    raise SystemExit(44)
print(ipa)
PY
)"

credentials_root="$signing_dir/appstoreconnect"
private_keys_dir="$credentials_root/private_keys"
key_file=""
public_key_file="$credentials_root/appstoreconnect-public-key.pem"
mkdir -p "$private_keys_dir" "$log_dir"
chmod 700 "$credentials_root" "$private_keys_dir"

cleanup_credentials() {
  unset XBUILD_ASC_APP_PASSWORD || true
  if [[ -n "$key_file" ]]; then
    rm -f -- "$key_file"
  fi
  rm -f -- "$public_key_file"
  rmdir "$private_keys_dir" "$credentials_root" >/dev/null 2>&1 || true
}
trap cleanup_credentials EXIT

if [[ "$auth_method" == "api-key" ]]; then
  key_file="$private_keys_dir/AuthKey_${key_id}.p8"
  XBUILD_DECODE_VALUE="$private_key_base64" XBUILD_DECODE_PATH="$key_file" python3 - <<'PY'
import base64
import os
import pathlib

value = "".join(os.environ["XBUILD_DECODE_VALUE"].split())
try:
    payload = base64.b64decode(value, validate=True)
except Exception as exc:
    print(f"::error title=App Store Connect key decode failed::{exc}")
    raise SystemExit(44)
pathlib.Path(os.environ["XBUILD_DECODE_PATH"]).write_bytes(payload)
PY
  chmod 600 "$key_file"

  if ! openssl pkey -in "$key_file" -noout </dev/null; then
    echo "::error title=Invalid App Store Connect private key::The .p8 secret is not a readable unencrypted private key."
    exit 44
  fi
  if ! openssl ec -in "$key_file" -pubout -out "$public_key_file" >/dev/null 2>&1 ||
     ! openssl ec -pubin -in "$public_key_file" -text -noout 2>/dev/null |
       grep -E 'ASN1 OID: prime256v1|NIST CURVE: P-256' >/dev/null; then
    rm -f -- "$public_key_file"
    echo "::error title=Invalid App Store Connect private key::The .p8 must use the EC P-256 curve."
    exit 44
  fi
  rm -f -- "$public_key_file"
fi

# Build an argument array directly: no eval, shell interpolation, or command
# string. --team-id disambiguates Apple accounts belonging to multiple teams.
altool_args=(
  altool
  --upload-app
  --file "$ipa_path"
  --type ios
)
if [[ "$auth_method" == "api-key" ]]; then
  altool_args+=(--apiKey "$key_id" --apiIssuer "$issuer_id")
  echo "Authentication: App Store Connect API key."
else
  # @env keeps the app-specific password out of altool's process arguments.
  altool_args+=(
    --username "$apple_id"
    --password "@env:XBUILD_ASC_APP_PASSWORD"
    --team-id "$team_id"
  )
  echo "Authentication: Apple ID + app-specific password (Team ID selected automatically)."
fi

# Remove original secret environment names before invoking altool.
unset private_key_base64 XBUILD_ASC_PRIVATE_KEY_BASE64
unset XBUILD_ASC_KEY_ID XBUILD_ASC_ISSUER_ID
unset XBUILD_TESTFLIGHT_AUTH_METHOD XBUILD_APPLE_ID XBUILD_APP_SPECIFIC_PASSWORD
unset XBUILD_APPLE_TEAM_ID

redact_output() {
  XBUILD_REDACT_1="$key_id" XBUILD_REDACT_2="$issuer_id" XBUILD_REDACT_3="$apple_id" XBUILD_REDACT_4="$app_specific_password" python3 -u -c '
import os
import sys

secrets = [os.environ.get(f"XBUILD_REDACT_{index}", "") for index in range(1, 5)]
secrets = [secret for secret in secrets if secret]
for line in sys.stdin:
    for secret in secrets:
        line = line.replace(secret, "[REDACTED]")
    sys.stdout.write(line)
    sys.stdout.flush()
'
}

echo "::group::Upload App Store IPA to TestFlight"
echo "Uploading $(basename "$ipa_path") to App Store Connect..."
set +e
(
  cd "$credentials_root"
  if [[ "$auth_method" == "apple-id" ]]; then
    XBUILD_ASC_APP_PASSWORD="$app_specific_password" xcrun "${altool_args[@]}"
  else
    xcrun "${altool_args[@]}"
  fi
) 2>&1 | redact_output | tee "$log_dir/testflight-upload.log"
upload_status=${PIPESTATUS[0]}
set -e
echo "::endgroup::"

if (( upload_status != 0 )); then
  echo "::error title=TestFlight upload failed::altool exited with status $upload_status. The Ad Hoc IPA remains in the GitHub artifact."
  exit "$upload_status"
fi

echo "::notice title=TestFlight upload accepted::Apple received the build. Processing in App Store Connect continues asynchronously."
